draw_set_color(c_black)
draw_set_font(global.fnt_pixel)
draw_set_halign(fa_middle)
draw_set_valign(fa_middle)
draw_text(570, 300, "testing testing testing")
draw_text(570, 600, "testing testing testing")
draw_text(570, 900, "testing testing testing")